name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create deployment package
      run: |
        zip -r deploy.zip ./* 

    - name: Copy deployment package to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "deploy.zip"
        target: "/tmp"

    - name: Deploy and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 创建临时目录
          mkdir -p /tmp/deploy_temp
          
          # 解压文件到临时目录
          unzip -o /tmp/deploy.zip -d /tmp/deploy_temp
          
          # 停止容器
          docker stop invoify || true
          
          # 清理并准备目标目录
          rm -rf /opt/1panel/docker/compose/invoify/*
          mkdir -p /opt/1panel/docker/compose/invoify
          
          # 移动文件到目标目录
          mv /tmp/deploy_temp/* /opt/1panel/docker/compose/invoify/
          
          # 清理临时文件
          rm -rf /tmp/deploy_temp
          rm -f /tmp/deploy.zip
          
          # 启动容器
          docker start invoify
          
          # 等待容器启动
          sleep 10
          
          # 在容器内执行安装命令
          docker exec invoify bash -c '
            cd /app && \
            npm install && \
            apt-get update && \
            apt-get install -y \
              libnss3 \
              libglib2.0-0 \
              libatk1.0-0 \
              libcups2 \
              libdbus-1-3 \
              libexpat1 \
              libfontconfig1 \
              libgbm1 \
              libgtk-3-0 \
              libpango-1.0-0 \
              libx11-xcb1 \
              libxcomposite1 \
              libxdamage1 \
              libxkbcommon0 \
              libxrandr2 \
              libasound2 \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*
          '
